#服务器端口
server:
  port: 8888

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_zhaoshuang?characterEncoding=utf8&useSSL=false
    username: root
    password: 789789
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml
  type-aliases-package: com.zhaoshuang.model
  global-config:
    db-config:
      id-type: auto
      db-type: mysql
      field-strategy: not_null
      column-underline: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      lazy-loading-enabled: true
      multiple-result-sets-enabled: true

