#服务器端口
server:
  port: 8888

#数据库配置
spring:
  datasource:
    #TODO 修改你的数据库连接地址
    url: jdbc:oracle:thin:@localhost:1521:orcl
    #TODO 修改你的数据库username
    username: root
    #TODO 修改你的数据库密码
    password: root
    #TODO 修改你的数据库连接驱动
    driver-class-name: oracle.jdbc.driver.OracleDriver


##   mysql使用的配置
#    url: jdbc:mysql://localhost:3306/db_zhaoshuang?characterEncoding=utf8&useSSL=false
#    username: root
#    password: 789789
#    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml
  type-aliases-package: com.zhaoshuang.model
  global-config:
    db-config:
      id-type: auto
      #db-type: mysql
      db-type: oracle
      field-strategy: not_null
      column-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    call-setters-on-nulls: true

